"use client";
import { Inter } from "next/font/google";

import Navbar from "../../components/navbar/Navbar";
// import Home from "../../components/landing/Home";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Navbar />
      <main>
        <div id="#home">{/* <Home /> */}</div>
      </main>
      {children}
    </div>
  );
}
